name: List Changed Files
run-name: List updated HTML files in commit ${{ github.sha }} ${{ github.event.after }}


on:
  push:
    branches:
      - main
    paths:  #the paths filters the workflow to run only when changes occur in specific files or directories.
      - "htmlForTranslation/**.html"
jobs:
  changed_files:
    runs-on: ubuntu-latest 
    name: List changed files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37


      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done