# This is a basic workflow to help you get started with Actions

name: Convert MD to HTML
run-name: Push [${{ github.ref_name }}] ${{ github.event.after }}

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    paths:
      - "public/**-en.html"
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: get all changed files
      - id: files
        uses: jitterbit/get-changed-files@v1 
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done
