# This is a basic workflow to help you get started with Actions

name: Convert MD to HTML
run-name: Push [${{ github.ref_name }}] ${{ github.event.after }}

# Controls when the workflow will run
on:
  push:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: jitterbit/get-changed-files@v1 
        id: files
        with: 
          format: space-delimited
      - name: Printing
        run: |
            echo "All:"
            echo "${{ steps.abc.outputs.all }}"
            echo "Added:"
            echo "${{ steps.abc.outputs.added }}"
            echo "Removed:"
            echo "${{ steps.abc.outputs.removed }}"
            echo "Renamed:"
            echo "${{ steps.abc.outputs.renamed }}"
            echo "Modified:"
            echo "${{ steps.abc.outputs.modified }}"
            echo "Added+Modified:"
            echo "${{ steps.abc.outputs.added_modified }}"
