name: List and Upload Changed Files
run-name: Files from ${{ github.event.head_commit.message }} ${{ github.event.after }}


on:
  push:
    branches:
      - main
    paths:  #the paths filters the workflow to run only when changes occur in specific files or directories.
      - "htmlForTranslation/**.html"
jobs:
  changed_files:
    runs-on: ubuntu-latest 
    name: List and upload changed files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37


      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
  
      - name: Install Lokalise CLI
        run: curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
      
      - name: Push to Lokalise
        env:
          GITHUB_BRANCH_NAME: ${{ github.ref_name }}
          GITHUB_PREVIOUS_COMMIT: ${{ github.event.after }}
          GITHUB_CURRENT_COMMIT: ${{ github.event.before }}
          VAR_LOKALISE_API_TOKEN: ${{ secrets.API_TOKEN }}
          VAR_LOKALISE_PROJECT_ID: ${{ vars.PROJECT_ID }}
          ENV_LOKALISE_SOURCE_LANG_ISO: en
        run: |
            uploaded_files=""
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
                  ./bin/lokalise2 --token ${{ env.VAR_LOKALISE_API_TOKEN }} --project-id ${{ env.VAR_LOKALISE_PROJECT_ID }} file upload --file="${file}" --lang-iso ${{ env.ENV_LOKALISE_SOURCE_LANG_ISO }} --replace-modified --include-path --use-automations=true --cleanup-mode --poll-timeout 120s
                  uploaded_files="${uploaded_files}${file}\n"
            done
            echo "Uploaded files to Lokalise:"
            echo -e "$uploaded_files"
